### ISSUE TITLE
Using wildcards in the Transformations doesn't work in my case

### ISSUE THREAD

**Issue by frankvaneykelen** [qetza/vsts-xdttransform-task#19]
I'm using this task to transform `.csproj` files (adding a `Content Include="foo.txt" />`) during the build and I wanted to use a wildcard for the project file name, but with the way wildcards work now I can't.

This works:
```
ProjectXtdTransformAddPipelineInfo.xml => $(ProjectFileName)
```

$(ProjectFileName) is set in preceding task with:
```
$ProjectFileName = (Get-ChildItem -Path $(build.sourcesDirectory)' -Filter *.csproj).Name

Write-Host "##vso[task.setvariable variable=ProjectFileName]$ProjectFileName"
```

Something like this will not work:
```
*AddPipelineInfo.xml => *.csproj
```
because that will look for a file named `ProjectXtdTransform.csproj` with how the code works now (which is made for handling web.release.config)

Sidenote - this is my XDT:
```xml
<?xml version="1.0"?>
<Project xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup xdt:Transform="Insert">
    <Content Include="pipeline-info.txt" />
  </ItemGroup>
</Project>
```

**Comment by qetza** [comment]
Hi @frankvaneykelen,

Sorry for the late reply.

This is the expected behavior as the `*` in the target part is not really a wildcard but more a token replaced with the value of the result of the wildcard in the transform part. This is to avoid issues where having wildcard in both parts would results in applying all transforms to all targets which could result in unexpected issues.

If you need to apply a transform to multiple dynamic targets then the best solution is to generate the transform expression in a task before as you did. Be careful though that if you have multiple .csproj you need to generate one line per csproj file with the full syntax (transform => target) and give this variables to transform task.

**Comment by frankvaneykelen** [comment]
Thanks
