### ISSUE TITLE
How to use in TFS Release with Web deploy?

### ISSUE THREAD

**Issue by AThomsen** [qetza/vsts-xdttransform-task#6]
Not sure if creating an issue is the right way to ask questions, but here goes :smile: 

Is this plugin supposed to work in the following scenario and, if so, how?
1. Use TFS Build to build a ASP.NET project to a web deploy package. Include web.configs for all environments in the drop.
2. Use TFS Release to deploy the package to IIS (WinRM + WebDeploy).
3. Transform web.config on release-time.

**Comment by qetza** [comment]
Hi @AThomsen,
WebDeploy supports by default xdt transformations:

- https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/visual-studio-web-deployment/web-config-transformations
- https://docs.microsoft.com/en-us/aspnet/web-forms/overview/deployment/visual-studio-web-deployment/deploying-to-iis

But i would no recommand this as it means that all your values (including sensitive values like password) are stored in your transformation files and in your source control.

If you want to use per environment values, webdeploy and IIS deploy task through WinRM i would recommand the following steps:

- have a single transformation file which will replace your local dev values with tokens and do other changes
- during build
  - generate your webdeploy package (without applying transformations)
  - store your package and your transformation file
- during release
  - unzip the webdeploy package
  - apply transformation using the XDT Transform task (this will inject your tokens in the web.config file and other changes)
  - replace tokens with values coming from TFS Release (which can be secured) using the task [Replace Tokens](https://marketplace.visualstudio.com/items?itemName=qetza.replacetokens)
  - zip the webdeploy package
  - deploy the updated package to IIS

**Comment by AThomsen** [comment]
I was just hoping for a way that didn't involve unzipping and zipping but this seems like the way to go 👍

**Comment by AThomsen** [comment]
We're now looking at using Replace Tokens instead and I think we'll face the same issue - having to unzip transform/replace and then zip again before deploying.

Is this the way these plugins are meant to work or am I missing something when it comes to deploying web applications to IIS?

**Comment by qetza** [comment]
Hi @AThomsen,

WebDeploy wasn't really meant to work with other tools. What i usually do for my asp.net projects is the following:
- at build time
  - use the publish settings to generate the `_PublishWebSites` folder with the files only
  - zip it manually and adda custom deploy powershell script (because usually web sites have a lot of files)
- at release time
  - unzip, transform xml, replace tokens and zip again (because i will need to copy the files)
  - copy files to IIS server
  - on server, unzip, run powershell script to copy files where needed
  - use IIS Web App Management task to create/update website and app pool
